### ISSUE TITLE
FilePreviews

### ISSUE THREAD

**Issue by jpadilla** [theantichris/digital-decoder-ring#1]
I'm one of the co-founders of FilePreviews. @gcollazo told me you were having some issues.

As far as I can see everything looks good, except that in [here](https://github.com/theantichris/digital-decoder-ring/blob/master/web/incoming.php#L13) it should be `api_key` instead of `apiKey`.

We also have some [docs](http://filepreviews.io/docs/endpoints.html), in case you missed those.

Let me know how that goes.

**Comment by theantichris** [comment]
I apologize for bothering you about such a silly mistake. I'm so use to a
certain naming convention I'm not sure I would have ever noticed that.
Thank you so much.,

On Tue, Jan 27, 2015 at 7:37 PM, José Padilla <notifications@github.com>
wrote:

> I'm one of the co-founders of FilePreviews. @gcollazo
> <https://github.com/gcollazo> told me you were having some issues.
>
> As far as I can see everything looks good, except that in here
> <https://github.com/theantichris/digital-decoder-ring/blob/master/web/incoming.php#L13>
> it should be api_key instead of apiKey.
>
> We also have some docs <http://filepreviews.io/docs/endpoints.html>, in
> case you missed those.
>
> Let me know how that goes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theantichris/digital-decoder-ring/issues/1>.
>



-- 

Christopher Lamm
theantichris.com

**Comment by jpadilla** [comment]
@theantichris not at all, let me know if there's anything else I can help you with.
